version: '3.7'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - nats
      - kafka
      - rabbitmq
  nats:
    image: nats
    ports:
      - "4222:4222"
  kafka:
    image: apache/kafka
    ports:
      - "9092:9092"
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
