version: '3.7'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - nats
      - kafka
  nats:
    image: nats
    ports:
      - "4222:4222"
  kafka:
    image: apache/kafka
    ports:
      - "9092:9092"
